// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Nhom6_QLHoSoTuyenDung.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250727170107_diemquynh")]
    partial class diemquynh
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nhom6_QLHoSoTuyenDung.Models.Entities.DanhGiaPhongVan", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id");

                    b.Property<string>("DeXuat")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("de_xuat");

                    b.Property<float?>("DiemDanhGia")
                        .HasColumnType("real")
                        .HasColumnName("diem_danh_gia");

                    b.Property<float?>("GiaiQuyetVanDe")
                        .HasColumnType("real")
                        .HasColumnName("giai_quyet_van_de");

                    b.Property<float?>("GiaoTiep")
                        .HasColumnType("real")
                        .HasColumnName("giao_tiep");

                    b.Property<float?>("KyNangChuyenMon")
                        .HasColumnType("real")
                        .HasColumnName("ky_nang_chuyen_mon");

                    b.Property<string>("LichPhongVanId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("lich_phong_van_id");

                    b.Property<DateTime?>("NgayDanhGia")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_danh_gia");

                    b.Property<string>("NhanVienDanhGiaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("nhan_vien_danh_gia_id");

                    b.Property<string>("NhanXet")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nhan_xet");

                    b.Property<float?>("ThaiDoLamViec")
                        .HasColumnType("real")
                        .HasColumnName("thai_do_lam_viec");

                    b.Property<float?>("TinhThanHocHoi")
                        .HasColumnType("real")
                        .HasColumnName("tinh_than_hoc_hoi");

                    b.HasKey("Id");

                    b.HasIndex("LichPhongVanId");

                    b.HasIndex("NhanVienDanhGiaId");

                    b.ToTable("DanhGiaPhongVans");
                });

            modelBuilder.Entity("Nhom6_QLHoSoTuyenDung.Models.Entities.HoSoLuuTru", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id");

                    b.Property<string>("LyDoLuuTru")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ly_do_luu_tru");

                    b.Property<DateTime?>("NgayLuu")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_luu");

                    b.Property<string>("UngVienId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ung_vien_id");

                    b.Property<string>("ViTriId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("vi_tri_id");

                    b.HasKey("Id");

                    b.HasIndex("UngVienId");

                    b.HasIndex("ViTriId");

                    b.ToTable("HoSoLuuTrus");
                });

            modelBuilder.Entity("Nhom6_QLHoSoTuyenDung.Models.Entities.LichPhongVan", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ghi_chu");

                    b.Property<string>("PhongPhongVanId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("phong_phong_van_id");

                    b.Property<DateTime?>("ThoiGian")
                        .HasColumnType("datetime2")
                        .HasColumnName("thoi_gian");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("trang_thai");

                    b.Property<string>("UngVienId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ung_vien_id");

                    b.Property<string>("UngVienMaUngVien")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ViTriId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("vi_tri_id");

                    b.Property<string>("ViTriTuyenDungMaViTri")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PhongPhongVanId");

                    b.HasIndex("UngVienId");

                    b.HasIndex("UngVienMaUngVien");

                    b.HasIndex("ViTriId");

                    b.HasIndex("ViTriTuyenDungMaViTri");

                    b.ToTable("LichPhongVans");
                });

            modelBuilder.Entity("Nhom6_QLHoSoTuyenDung.Models.Entities.NguoiDung", b =>
                {
                    b.Property<string>("NhanVienId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("nhan_vien_id");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ho_ten");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mat_khau");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_tao");

                    b.Property<string>("PhongBanId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("phong_ban_id");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sdt");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ten_dang_nhap");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("vai_tro");

                    b.HasKey("NhanVienId");

                    b.HasIndex("PhongBanId");

                    b.ToTable("NguoiDungs");
                });

            modelBuilder.Entity("Nhom6_QLHoSoTuyenDung.Models.Entities.NhanVien", b =>
                {
                    b.Property<string>("MaNhanVien")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id");

                    b.Property<string>("ChucVu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("chuc_vu");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ho_ten");

                    b.Property<string>("KinhNghiem")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("kinh_nghiem");

                    b.Property<string>("MaSoNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ma_nv");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mo_ta");

                    b.Property<float?>("MucLuong")
                        .HasColumnType("real")
                        .HasColumnName("muc_luong");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_sinh");

                    b.Property<DateTime?>("NgayVaoCongTy")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_vao_cty");

                    b.Property<string>("PhongBanId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("phong_ban_id");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sdt");

                    b.HasKey("MaNhanVien");

                    b.HasIndex("PhongBanId");

                    b.ToTable("NhanViens");
                });

            modelBuilder.Entity("Nhom6_QLHoSoTuyenDung.Models.Entities.NhanVienThamGiaPhongVan", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id");

                    b.Property<string>("LichPhongVanId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("lich_phong_van_id");

                    b.Property<string>("NhanVienId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("nhan_vien_id");

                    b.Property<string>("VaiTro")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("vai_tro");

                    b.HasKey("Id");

                    b.HasIndex("LichPhongVanId");

                    b.HasIndex("NhanVienId");

                    b.ToTable("NhanVienThamGiaPhongVans");
                });

            modelBuilder.Entity("Nhom6_QLHoSoTuyenDung.Models.Entities.PhongBan", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mo_ta");

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ten_phong");

                    b.HasKey("Id");

                    b.ToTable("PhongBans");
                });

            modelBuilder.Entity("Nhom6_QLHoSoTuyenDung.Models.Entities.PhongPhongVan", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id");

                    b.Property<string>("DiaDiem")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("dia_diem");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mo_ta");

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ten_phong");

                    b.HasKey("Id");

                    b.ToTable("PhongPhongVans");
                });

            modelBuilder.Entity("Nhom6_QLHoSoTuyenDung.Models.Entities.UngVien", b =>
                {
                    b.Property<string>("MaUngVien")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<int>("GioiTinh")
                        .HasColumnType("int")
                        .HasColumnName("gioi_tinh");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ho_ten");

                    b.Property<string>("KinhNghiem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("kinh_nghiem");

                    b.Property<string>("LinkCV")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("link_cv");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mo_ta");

                    b.Property<DateTime?>("NgayNop")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_nop");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_sinh");

                    b.Property<string>("NguonUngTuyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nguon_ung_tuyen");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sdt");

                    b.Property<string>("ThanhTich")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("thanh_tich");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("trang_thai");

                    b.Property<string>("ViTriUngTuyenId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("vi_tri_ung_tuyen_id");

                    b.HasKey("MaUngVien");

                    b.HasIndex("ViTriUngTuyenId");

                    b.ToTable("UngViens");
                });

            modelBuilder.Entity("Nhom6_QLHoSoTuyenDung.Models.Entities.ViTriTuyenDung", b =>
                {
                    b.Property<string>("MaViTri")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id");

                    b.Property<string>("KyNang")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ky_nang");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_tao");

                    b.Property<string>("PhongBanId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("phong_ban_id");

                    b.Property<int?>("SoLuongCanTuyen")
                        .HasColumnType("int")
                        .HasColumnName("so_luong_can_tuyen");

                    b.Property<string>("TenViTri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ten_vi_tri");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaViTri");

                    b.HasIndex("PhongBanId");

                    b.ToTable("ViTriTuyenDungs");
                });

            modelBuilder.Entity("Nhom6_QLHoSoTuyenDung.Models.Entities.DanhGiaPhongVan", b =>
                {
                    b.HasOne("Nhom6_QLHoSoTuyenDung.Models.Entities.LichPhongVan", "LichPhongVan")
                        .WithMany("DanhGiaPhongVans")
                        .HasForeignKey("LichPhongVanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nhom6_QLHoSoTuyenDung.Models.Entities.NhanVien", "NhanVienDanhGia")
                        .WithMany()
                        .HasForeignKey("NhanVienDanhGiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LichPhongVan");

                    b.Navigation("NhanVienDanhGia");
                });

            modelBuilder.Entity("Nhom6_QLHoSoTuyenDung.Models.Entities.HoSoLuuTru", b =>
                {
                    b.HasOne("Nhom6_QLHoSoTuyenDung.Models.Entities.UngVien", "UngVien")
                        .WithMany("HoSoLuuTrus")
                        .HasForeignKey("UngVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nhom6_QLHoSoTuyenDung.Models.Entities.ViTriTuyenDung", "ViTriTuyenDung")
                        .WithMany()
                        .HasForeignKey("ViTriId");

                    b.Navigation("UngVien");

                    b.Navigation("ViTriTuyenDung");
                });

            modelBuilder.Entity("Nhom6_QLHoSoTuyenDung.Models.Entities.LichPhongVan", b =>
                {
                    b.HasOne("Nhom6_QLHoSoTuyenDung.Models.Entities.PhongPhongVan", "PhongPhongVan")
                        .WithMany("LichPhongVans")
                        .HasForeignKey("PhongPhongVanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nhom6_QLHoSoTuyenDung.Models.Entities.UngVien", "UngVien")
                        .WithMany()
                        .HasForeignKey("UngVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nhom6_QLHoSoTuyenDung.Models.Entities.UngVien", null)
                        .WithMany("LichPhongVans")
                        .HasForeignKey("UngVienMaUngVien");

                    b.HasOne("Nhom6_QLHoSoTuyenDung.Models.Entities.ViTriTuyenDung", "ViTriTuyenDung")
                        .WithMany()
                        .HasForeignKey("ViTriId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nhom6_QLHoSoTuyenDung.Models.Entities.ViTriTuyenDung", null)
                        .WithMany("LichPhongVans")
                        .HasForeignKey("ViTriTuyenDungMaViTri");

                    b.Navigation("PhongPhongVan");

                    b.Navigation("UngVien");

                    b.Navigation("ViTriTuyenDung");
                });

            modelBuilder.Entity("Nhom6_QLHoSoTuyenDung.Models.Entities.NguoiDung", b =>
                {
                    b.HasOne("Nhom6_QLHoSoTuyenDung.Models.Entities.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nhom6_QLHoSoTuyenDung.Models.Entities.PhongBan", "PhongBan")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("PhongBanId");

                    b.Navigation("NhanVien");

                    b.Navigation("PhongBan");
                });

            modelBuilder.Entity("Nhom6_QLHoSoTuyenDung.Models.Entities.NhanVien", b =>
                {
                    b.HasOne("Nhom6_QLHoSoTuyenDung.Models.Entities.PhongBan", "PhongBan")
                        .WithMany("NhanViens")
                        .HasForeignKey("PhongBanId");

                    b.Navigation("PhongBan");
                });

            modelBuilder.Entity("Nhom6_QLHoSoTuyenDung.Models.Entities.NhanVienThamGiaPhongVan", b =>
                {
                    b.HasOne("Nhom6_QLHoSoTuyenDung.Models.Entities.LichPhongVan", "LichPhongVan")
                        .WithMany("NhanVienThamGiaPVs")
                        .HasForeignKey("LichPhongVanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nhom6_QLHoSoTuyenDung.Models.Entities.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LichPhongVan");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("Nhom6_QLHoSoTuyenDung.Models.Entities.UngVien", b =>
                {
                    b.HasOne("Nhom6_QLHoSoTuyenDung.Models.Entities.ViTriTuyenDung", "ViTriUngTuyen")
                        .WithMany("UngViens")
                        .HasForeignKey("ViTriUngTuyenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ViTriUngTuyen");
                });

            modelBuilder.Entity("Nhom6_QLHoSoTuyenDung.Models.Entities.ViTriTuyenDung", b =>
                {
                    b.HasOne("Nhom6_QLHoSoTuyenDung.Models.Entities.PhongBan", "PhongBan")
                        .WithMany("ViTriTuyenDungs")
                        .HasForeignKey("PhongBanId");

                    b.Navigation("PhongBan");
                });

            modelBuilder.Entity("Nhom6_QLHoSoTuyenDung.Models.Entities.LichPhongVan", b =>
                {
                    b.Navigation("DanhGiaPhongVans");

                    b.Navigation("NhanVienThamGiaPVs");
                });

            modelBuilder.Entity("Nhom6_QLHoSoTuyenDung.Models.Entities.PhongBan", b =>
                {
                    b.Navigation("NguoiDungs");

                    b.Navigation("NhanViens");

                    b.Navigation("ViTriTuyenDungs");
                });

            modelBuilder.Entity("Nhom6_QLHoSoTuyenDung.Models.Entities.PhongPhongVan", b =>
                {
                    b.Navigation("LichPhongVans");
                });

            modelBuilder.Entity("Nhom6_QLHoSoTuyenDung.Models.Entities.UngVien", b =>
                {
                    b.Navigation("HoSoLuuTrus");

                    b.Navigation("LichPhongVans");
                });

            modelBuilder.Entity("Nhom6_QLHoSoTuyenDung.Models.Entities.ViTriTuyenDung", b =>
                {
                    b.Navigation("LichPhongVans");

                    b.Navigation("UngViens");
                });
#pragma warning restore 612, 618
        }
    }
}
